# Generated by Django 3.0.8 on 2020-09-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_auto_20200823_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=454)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('books', models.ManyToManyField(to='products.Book')),
            ],
        ),
    ]
