# Generated by Django 3.1.1 on 2020-09-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_plan_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan_duration',
        ),
    ]
