# Generated by Django 3.1.1 on 2020-09-27 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20200920_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_duration',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
