# Generated by Django 3.0.8 on 2020-08-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200818_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publ_year',
            new_name='publication_year',
        ),
    ]
